### ISSUE TITLE
Latest docker image not works

### ISSUE THREAD

**Issue by manuelmazzuola** [hmalphettes/kibana-proxy#10]
Hi,
Can you check the latest docker image ?
Seems that the npm _postinstall_ script has not been executed.
Kibana folder is missing.

Thanks

**Comment by hmalphettes** [comment]
Many thanks for reporting this! I am using the image to proxy the plugins but I had not not checked on kibana.

**Comment by hmalphettes** [comment]
kibana is in the latest docker image and working for me.
Cheers!
