### ISSUE TITLE
How to reach kibana-proxy through the apache-proxy

### ISSUE THREAD

**Issue by PavelPolyakov** [hmalphettes/kibana-proxy#8]
Hi there,

I'm trying to make the kibana-proxy instance (which helps me to interact with the secured  elasticsearch) through the apache-proxy:

~~~
Options +FollowSymLinks
RewriteEngine On
RewriteBase /kibana/

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule (.*) - [L]

RewriteRule ^(.*)$ http://127.0.0.1:3003/$1 [P]
~~~

But it fails here:
~~~
Request URL:http://my-server.com/__es/_nodes
Request Method:GET
Status Code:404 Not Found
Request Headersview source
~~~

Do we have any changes to make it work from the folder under apache?

Regards,

**Comment by hmalphettes** [comment]
Hi!

I actually don't have experience doing this.
I suspect that using a base path to differentiate the requests for kibana/es wont work well though.
At least it wont work well with the ES plugins unless you change the base URL too... Let us know if you got somehwere with this.

I know having a reverse-proxy in front of kibana-proxy works nicely using virtual hosts and that is what I am doing with a containerised nginx:
https://github.com/jwilder/nginx-proxy

I hope this helps.
